[tool.poetry]
name = "y2b"
version = "0.1.0"
description = ""
authors = ["Leo Zhou <glasslion@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"
click = "^7.0"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
